---
kind: pipeline
type: docker
name: default

steps:
  - name: setup
    image: node:16-alpine
    when:
      event:
        - push
    commands:
      - yarn --frozen-lockfile

        # - name: prettier
        #   image: node:16-alpine
        #   when:
        #     event:
        #       - push
        #   depends_on:
        #     - setup
        #   commands:
        #     - yarn prettier:check

        # - name: eslint
        #   image: node:16-alpine
        #   when:
        #     event:
        #       - push
        #   depends_on:
        #     - setup
        #   commands:
        #     - yarn eslint

  - name: build
    image: node:16-alpine
    when:
      event:
        - push
    depends_on:
      - setup
    commands:
      - yarn build

  - name: docker
    image: plugins/docker
    when:
      branch:
        - master
      event:
        - push
      status:
        - success
    depends_on:
      - setup
        #- prettier
        #- eslint
      - build
    settings:
      registry: https://registry.webkom.dev
      repo: registry.webkom.dev/webkom/ababart
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
      build_args:
        - RELEASE=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}

  - name: Deploy
    image: abakus/ansible-deploy
    when:
      branch:
        - master
      event: push
      status: success
    settings:
      playbook: /infrastructure/esas/playbooks/deploy.yml
      repository:
        from_secret: infra_repository
      tags:
        - yourls
      limit: esas
      inventory: /infrastructure/inventory
      vault_password:
        from_secret: ansible_vault_password
      private_key:
        from_secret: infra_deploy_key
    depends_on:
      - docker
